### ISSUE TITLE
UnsatisfiedLinkError: 'int com.jme3.bullet.util.NativeLibrary.countThreads()'

### ISSUE THREAD

**Issue by KianBrose** [stephengold/Libbulletjme#33]
Hello!

I am getting this really weird error after like 10 seconds of running the program:

```
java.lang.RuntimeException: Exception in scheduled task
	at net.minestom.server.timer.SchedulerImpl.handleTask(SchedulerImpl.java:113)
	at net.minestom.server.timer.SchedulerImpl.lambda$runTasks$3(SchedulerImpl.java:72)
	at org.jctools.queues.MessagePassingQueueUtil.drain(MessagePassingQueueUtil.java:39)
	at org.jctools.queues.BaseMpscLinkedArrayQueue.drain(BaseMpscLinkedArrayQueue.java:612)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:23)
	at org.jctools.queues.MpscUnboundedArrayQueue.drain(MpscUnboundedArrayQueue.java:63)
	at net.minestom.server.timer.SchedulerImpl.runTasks(SchedulerImpl.java:69)
	at net.minestom.server.timer.SchedulerImpl.processTickTasks(SchedulerImpl.java:63)
	at net.minestom.server.timer.SchedulerImpl.processTick(SchedulerImpl.java:46)
	at net.minestom.server.timer.SchedulerImpl.processTick(SchedulerImpl.java:42)
	at net.minestom.server.instance.Instance.tick(Instance.java:665)
	at net.minestom.server.instance.InstanceContainer.tick(InstanceContainer.java:596)
	at net.minestom.server.ServerProcessImpl$TickerImpl.serverTick(ServerProcessImpl.java:297)
	at net.minestom.server.ServerProcessImpl$TickerImpl.tick(ServerProcessImpl.java:274)
	at net.minestom.server.thread.TickSchedulerThread.run(TickSchedulerThread.java:29)
Caused by: java.lang.UnsatisfiedLinkError: 'int com.jme3.bullet.util.NativeLibrary.countThreads()'
Caused by: java.lang.UnsatisfiedLinkError: 'int com.jme3.bullet.util.NativeLibrary.countThreads()'

	at com.jme3.bullet.util.NativeLibrary.countThreads(Native Method)
	at com.jme3.bullet.PhysicsSpace.<init>(PhysicsSpace.java:229)
	at com.jme3.bullet.PhysicsSpace.<init>(PhysicsSpace.java:199)
	at com.kianbrose.mcwarlobby.physics.MinecraftPhysicsHandler.lambda$new$1(MinecraftPhysicsHandler.java:58)
	at net.minestom.server.instance.Instance.lambda$scheduleNextTick$0(Instance.java:160)
	at net.minestom.server.timer.Task$Builder.lambda$new$0(Task.java:43)
	at net.minestom.server.timer.Task$Builder$1.get(Task.java:79)
	at net.minestom.server.timer.Task$Builder$1.get(Task.java:70)
	at net.minestom.server.timer.SchedulerImpl.handleTask(SchedulerImpl.java:111)
	... 14 more
```

The line 58 at `MinecraftPhysicsHandler` is as follows
```
physicsSpace = new PhysicsSpace(PhysicsSpace.BroadphaseType.DBVT);
```
Any idea why it broke?

When the program boots up, it should be loading the native libraties with this:
```
    public static void main(String[] args) {
        NativeLibraryLoader.loadLibbulletjme(true, new File("natives/"), "Release", "Sp");
```
The file `Linux64ReleaseSp_libbulletjme.so` is present.

**Comment by KianBrose** [comment]
I am stupid, I needed the MAC variant

**Comment by stephengold** [comment]
No worries---just glad you solved it.
